# docker-compose.override.yml - Development / Integration Testing
# Automatically used by `docker compose up`

services:
  airflow-webserver:
    environment:
      POSTGRES_TO_REDSHIFT_CONFIG_PATH: /opt/airflow/config/test/test_redshift_config.yaml
      ARCHIVE_POSTGRES_TO_S3_CONFIG_PATH: /opt/airflow/config/test/test_s3_config.yaml
      REST_TO_POSTGRES_CONFIG_PATH: /opt/airflow/config/test/test_rest_config.yaml
      POSTGRES_CLEANUP_CONFIG_PATH: /opt/airflow/config/test/test_cleanup_config.yaml
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__LOGGING__LOGGING_LEVEL: DEBUG

  airflow-scheduler:
    environment:
      POSTGRES_TO_REDSHIFT_CONFIG_PATH: /opt/airflow/config/test/test_redshift_config.yaml
      ARCHIVE_POSTGRES_TO_S3_CONFIG_PATH: /opt/airflow/config/test/test_s3_config.yaml
      REST_TO_POSTGRES_CONFIG_PATH: /opt/airflow/config/test/test_rest_config.yaml
      POSTGRES_CLEANUP_CONFIG_PATH: /opt/airflow/config/test/test_cleanup_config.yaml
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__LOGGING__LOGGING_LEVEL: DEBUG

    volumes:
      - ./config:/opt/airflow/config:ro
      - ./airflow/dags:/app/airflow/dags:cached
      - ./airflow/plugins:/app/airflow/plugins:cached

    healthcheck:
      start_period: 30s
      interval: 15s

  localstack:
    environment:
      DEBUG: ${LOCALSTACK_DEBUG:-1}
      DISABLE_CORS_CHECKS: 1
      SKIP_INFRA_DOWNLOADS: 1
      SERVICES: s3,secretsmanager,ssm,logs,cloudwatch
      LAMBDA_EXECUTOR: local
      LOCALSTACK_HOSTNAME: localstack

    healthcheck:
      start_period: 15s
      interval: 15s

  redshift_sim:
    environment:
      POSTGRES_MAX_CONNECTIONS: 50
      POSTGRES_LOG_STATEMENT: all
      POSTGRES_LOG_MIN_DURATION_STATEMENT: 0

    volumes:
      - ./sql/redshift:/app/sql:ro

    healthcheck:
      start_period: 15s
      interval: 5s

  db:
    environment:
      POSTGRES_MAX_CONNECTIONS: 50

    volumes:
      - ./db/dev-init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      start_period: 15s
      interval: 5s

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION:-latest}
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    networks:
      - etl_net
    depends_on:
      - db
      - redshift_sim
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

volumes:
  pgadmin_data:
    driver: local
