services:
  airflow:
    environment:
      ARCHIVE_POSTGRES_TO_S3_CONFIG_PATH: /opt/airflow/config/test/test_s3_config.yaml
      POSTGRES_TO_REDSHIFT_CONFIG_PATH: /opt/airflow/config/test/test_redshift_config.yaml
      REST_TO_POSTGRES_CONFIG_PATH: /opt/airflow/config/test/test_rest_config.yaml
      POSTGRES_CLEANUP_CONFIG_PATH: /opt/airflow/config/test/test_cleanup_config.yaml
      POSTGRES_CONFIG_PATH: /opt/airflow/config/test/test_postgres_config.yaml
    volumes:
      - ./config/test:/opt/airflow/config/test
