services:
  airflow-webserver:
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      ARCHIVE_POSTGRES_TO_S3_CONFIG_PATH: /opt/airflow/config/test/test_s3_config.yaml
    volumes:
      - ./config/test:/opt/airflow/config/test

  airflow-scheduler:
    environment:
      AWS_ACCESS_KEY_ID: dummy_access_key
      AWS_SECRET_ACCESS_KEY: dummy_secret_key
      AWS_REGION: us-east-1
      ARCHIVE_POSTGRES_TO_S3_CONFIG_PATH: /opt/airflow/config/test/test_s3_config.yaml
    volumes:
      - ./config/test:/opt/airflow/config/test

  localstack:
    image: localstack/localstack:3
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      SERVICES: s3
      DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - etl_net

  redshift_sim:
    image: postgres:16
    container_name: redshift_sim
    environment:
      POSTGRES_USER: redshift_user
      POSTGRES_PASSWORD: redshift_pass
      POSTGRES_DB: redshift_db
    ports:
      - "5433:5432"
    volumes:
      - redshift_data:/var/lib/postgresql/data
    networks:
      - etl_net
