# config.yaml file
api:
  endpoint: https://www.alphavantage.co/query
  key: your_api_key
  timeout: 30 # in seconds
  symbol: IBM
  interval: 5min

# Validation rules
validation:
  alpha_vantage_intraday:
    required_keys:
      - endpoint
      - key
      - timeout
      - symbol
      - interval

directories:
  raw_data: "../data/raw_data"
  processed_data: "../data/processed_data"

# Logging configuration (centralized, modern: STDOUT/JSON)
logging:
  level: DEBUG # Set log level: DEBUG, INFO, ERROR, etc.
  format: json # Structured logs (JSON) for aggregation/analysis
  # No log files needed for modern container logging

# Extract-specific configuration
extract:
  required_fields:
    - "1. open"
    - "2. high"
    - "3. low"
    - "4. close"
    - "5. volume"

# Transform-specific configuration
transform:
  required_fields:
    - "1. open"
    - "2. high"
    - "3. low"
    - "4. close"
    - "5. volume"

# Postgres Loader-specific configuration
postgres_loader:
  # Logging now handled globally; no file setting here
