# config.yaml 
api:
  endpoint: https://www.alphavantage.co/query
  key: ${ALPHA_VANTAGE_API_KEY}
  timeout: 30
  symbol: IBM
  interval: 5min

validation: 
  alpha_vantage_intraday:
    required_keys:
      - endpoint
      - key
      - timeout
      - symbol
      - interval

directories:
  raw_data: "../data/raw_data"
  processed_data: "../data/processed_data"
  dags: "../dags"
  logs: "../logs"

logging:
  level: DEBUG
  format: json

extract:
  required_fields:
    - "1. open"
    - "2. high"
    - "3. low"
    - "4. close"
    - "5. volume"

transform:
  required_fields:
    - "1. open"
    - "2. high"
    - "3. low"
    - "4. close"
    - "5. volume"

postgres_loader:
  schema: public
  table: your_target_table


s3:
  archive_bucket: your-archive-bucket-name
  logs_bucket: your-logs-bucket-name
  region: your-aws-region
  path_format: archive/{table}/dt={date}/{filename}



redshift:
  host: ${REDSHIFT_HOST}
  port: ${REDSHIFT_PORT}
  db: ${REDSHIFT_DB}
  schema: ${REDSHIFT_SCHEMA}
  table: ${REDSHIFT_TABLE}
  copy_options: "FORMAT AS JSON 'auto'"

airflow:
  executor: ${AIRFLOW__CORE__EXECUTOR}
  dags_folder: "../dags"
  logs_folder: "../logs"

notifications:
  email_on_failure: true
  email_on_retry: false
  recipients:
    - ${ALERT_EMAILS}
